name: Fetch Secret from Azure Key Vault

on:
  workflow_call:
    inputs:
      azure_credentials:
        required: true
        type: string
      key_vault_name:
        required: true
        type: string
      azure_resource_group:
        required: true
        type: string
      secrets_filter:
        required: false
        type: string

jobs:
  fetch-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug AZURE_CREDENTIALS
        run: |
          echo "AZURE_CREDENTIALS length: ${#AZURE_CREDENTIALS}"
          echo "${{ secrets.AZURE_CREDENTIALS }}" | jq 'keys'
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: "ffb93db2-adb3-4ef0-ab02-561badddfc03"
          client-secret: "6xo8Q~6oCqRZ_2ms.KUkReYyqMwr2gpDIbwsrand"
          subscription-id: "6bd6f6b7-40e3-4919-a31c-08946e2be7d3"
          tenant-id: "513294a0-3e20-41b2-a970-6d30bf1546fa"

      - name: Fetch Agent IP Address
        run: |
          if [[ "${{ runner.name }}" == "GitHub Actions" ]]; then
            agent_ip=$(curl -s ifconfig.me)
          else
            agent_ip=$(hostname -I | awk '{print $1}')
          fi
          echo "Agent IP Address: $agent_ip"
          echo "AGENT_IP=$agent_ip" >> $GITHUB_ENV

      - name: Whitelist Pipeline Agent IP on Azure Key Vault
        run: az keyvault network-rule add --name ${{ inputs.key_vault_name }} --ip-address $agent_ip --no-wait --resource-group ${{ inputs.azure_resource_group }}

      - name: Fetch Secret from Azure Key Vault
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ inputs.key_vault_name }}
          secrets: ${{ inputs.secrets_filter || '*' }}
